#ADDITION ON INTEGER
a = 32.4
b = 21
c = a+b#ADDITION CAN BE DONE WITH MIXTURE OF INT AND FLOAT BECAUSE BOTH ARE NUMBERS
print(c)

#ADDITION ON STRING
c = 'HELLO'#single or double any qoutes can be used here
d = 'DHRUV'
e = c+" "+d
print(e)
#ADDITION OPERATOR CANNOT BE USED WHERE WE HAVE MIX VALUES
#SUCH AS SOME VALUES OF INTEGER TYPE AND SOME OF STRING TYPE
#LET'S SAY WE HAVE A=5 AND B="HELLO" AND WE DO A+B THEN IT WILL RESULT ERROR
