#WE CAN USE PYTHON AS A CALCULATOR VERY EASILY AS::
print(14+2*7+12)

#TWO DIVISION METHODS::
print(8/4)#IT GIVES FLOAT TYPE NUMBER
print(8//4)#IT GIVES INTEGER NUMBER

#EXPONENT(**)::
print(2**3)#** is exponent sign

#WE CAN FIND SQUARE ROOT OF A NUMBER USING EXPONENT SIGN AS::
print(4**0.5)#exponent 0.5 is called square root

#WE CAN PRINT A FIXED NUMBER OF DECIMAL VALUES USING round() FUNCTION AS ::
print(round(2**0.5,2)) #IN round FUNCTION,AFTER COMMA PUT THE VALUE AS TILL HOW MANY DECIMAL NUMBERS YOU WANT YOUR ANSWER

#MODULUS OPERATOR(%)::
print(5%2)#IT GIVES REMAINDER

#IF WE HAVE A LONG STATEMENT TO CALCULATE THEN PYTHON CALCULATES IT ACCORDING TO PRECEEDENCE AND ASSOCIATIVITY.
