name = input("ENTER YOUR NAME::")
print("HELLO "+name)
#EVERY TIME THE INPUT FUNCTION WILL TAKE THE VALUE IN STRING TYPE
age = input("ENTER YOUR AGE::")
print("YOUR AGE IS "+age)#THIS IS THE PROOF FOR EVERY VALUE IN INPUT FUNCTION IS STORED AS STRING TYPE AS IF THIS STTEMENT DO NOT RESULTS IN AN ERROR THEN IT MEANS THAT AGE IS STRING TYPE BECAUSE STRING CAN ONLY BE ADDED WITH A STRING 


num1 = input("ENTER FIRST NUMBER::")
num2 = input("ENTER SECOND NUMBER::")
num = num1+num2
print("TOTAL::"+num)
#HERE, THE OUTPUT WILL NOT BE THE SUM OF TWO VALUES AS BOTH THE VALUES ARE STRING TYPE,THE OUTPUT WILL BE THE CONCATENATION OF THE TWO VALUES ENTERED BY THE USER

#IF WE WANT SUM IN THE ABOVE CODE THEN WE SHOULD DECLARE BOTH INPUT VALUES AS INT::
num1 = int(input("ENTER FIRST NUMBER::"))
num2 = int(input("ENTER SECOND NUMBER::"))
num = num1+num2
print("TOTAL::"+str(num))#AS WE CANNOT CONCATENATE INTEGER AND STRING
#SO WE CHANGED THE NUM VARIABLE(WHICH WAS OF INT TYPE TO STRING TYPE SO THAT IT CAN BE CONCATENATED),USING STR() FUNCTION

num1 = int("23")
num2 = float("22")
total = print(num1+num2)
#IT MEANS THAT WE CAN ADD INTEGER TYPE AND FLOAT TYPE VALUE BUT NOT  WITH STRING TYPE
